apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-2001-via-enp2s0
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp2s0
        description: Linux Brige info COE Network via enp2s0
        ipv4:
          enabled: false
        name: br-2001
        state: up
        type: linux-bridge
  nodeSelector:
    node-role.kubernetes.io/worker: ""
