apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: localnet-via-br-ex
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: br-ex
          localnet: localnet-via-br-ex
          state: present
  nodeSelector:
    node-role.kubernetes.io/worker: ""
