---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opensift-examples
  name: opensift-examples
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: opensift-examples
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  labels:
    app: opensift-examples
    app.kubernetes.io/component: opensift-examples
    app.kubernetes.io/instance: opensift-examples
    app.kubernetes.io/part-of: opensift-examples
    app.openshift.io/runtime: openshift
  name: opensift-examples
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: opensift-examples
  template:
    metadata:
      labels:
        app: opensift-examples
    spec:
      containers:
      - image: quay.io/openshift-examples/web:master
        name: web
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 8081
      - args:
        - -nginx.scrape-uri=http://localhost:8081/
        image: docker.io/nginx/nginx-prometheus-exporter:latest
        name: nginx-prometheus-exporter
        ports:
        - containerPort: 9113
          name: metrics
        readinessProbe:
          httpGet:
            path: /
            port: 9113
