{{- if .Values.imageStream.create -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "openshift-examples-simple.imageStreamName" . }}
  labels:
    {{- include "openshift-examples-simple.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
