apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn-3
spec:
  namespaceSelector:
    matchLabels:
      tentant: tentant-3
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - 203.0.113.0/24
      ipam:
        lifecycle: Persistent
