apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simpson

resources:
- namespace.yaml
- homer-deployment.yaml
- homer-service.yaml
- homer-route.yaml
- marge-deployment.yaml
- marge-service.yaml
- marge-route.yaml

