---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      serviceAccountName: monitor
      automountServiceAccountToken: true
      containers:
      - image:  image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        name: monitor
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        # resources:
        #   limits:
        #     ephemeral-storage: 40Mi
        #     cpu: 0.1
        #     memory: "20Mi"
        #   requests:
        #     ephemeral-storage: 20Mi
        #     cpu: 0.1
        #     memory: "20Mi"
        command:
          - /bin/sh
          - -c
          - |

            HOMER_URL=$( oc get route -n simpson homer -o jsonpath="{.spec.host}" )
            MARGE_URL=$( oc get route -n simpson marge -o jsonpath="{.spec.host}" )
            SELMA_URL=$( oc get route -n bouvier selma -o jsonpath="{.spec.host}" )
            PATTY_URL=$( oc get route -n bouvier patty -o jsonpath="{.spec.host}" )
            while true; do
                echo "# =========================================================="
                echo -n "# "; date
                curl -s -k https://${HOMER_URL}/demo
                curl -s -k https://${MARGE_URL}/demo
                curl -s -k https://${SELMA_URL}/demo
                curl -s -k https://${PATTY_URL}/demo
                sleep 5;
            done;


  triggers:
  - type: ConfigChange
