FROM registry.access.redhat.com/ubi9/ubi:9.6

RUN dnf install -y lldpd iproute net-tools procps-ng \
  	&& dnf clean all \
  	&& rm -rf /var/cache/yum

USER 0

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/usr/sbin/lldpd -d $DAEMON_ARGS $LLDPD_OPTIONS"]
