apiVersion: v1
baseDomain: coe.muc.redhat.com
compute:
  - name: worker
    replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: sno-on-ocpv
networking:
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.128.0.0/14
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.31.0.0/16
platform:
  none: {}
bootstrapInPlace:
  installationDisk: /dev/vda
pullSecret: |
  {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3Jib2huZTFlY3hxbWhwamQ4bnU0cWk1NmNtc200NGh2ejpRUzlTNDM4TU5LVk1JSlhGR0xSVzZBSFZTMjdLTzBSV05NU0ZaSkRPUFVOQVkxR04xM0JDRzY0RUYzU1dGTVQx","email":"rbohne@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3Jib2huZTFlY3hxbWhwamQ4bnU0cWk1NmNtc200NGh2ejpRUzlTNDM4TU5LVk1JSlhGR0xSVzZBSFZTMjdLTzBSV05NU0ZaSkRPUFVOQVkxR04xM0JDRzY0RUYzU1dGTVQx","email":"rbohne@redhat.com"},"registry.connect.redhat.com":{"auth":"NTIxNzMzNzZ8dWhjLTFFQ3hxTUhQSkQ4TnU0cWk1NkNNU000NGh2ejpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZV001T0RKbVkyTm1PRFUwT1RaaFlUSTVaRFl6WkdFd1pUSmtaRFZoTmlKOS5sRy1DVmpLd2xKQUczMzFCY3F5dVloRXg3cHF6V2FDT1ZmdnBOSW45OGp1eDhXQXdPT0dzSGVvdlBrZU13RjJIOFdhWHc3ZEU3Snl6anppdmFodUhyN2loWlF1bjBqSGgwVnJRNHRlQjZiWE9RckNpTGpTVFZrd2g5QWJERVJzUnhwOFNpSkJrWjI3dDRicDB3SlB3WEZVZnB5T3JORjBmTkFsQU9pd2xQM1A5UThicjV1YUpHbHNpWnZyVjdkV0QwSHZuZk5GaVNMR0RKWGl1UFZqaEJKanp0ZlpBSDVKNU14eDFQdDRCZG9HeGlrUTFPdUNvdjd5bjc3Zm9EWkowX1lvRDM5Z21oWEZZMWdGQTctLTl1b1pHNmhqdFVuZy15WGRKQkkyTjZRcDV4dGRGRDJ4cTBmcklRWHE3WmVWWFJ1d0s5VmFhd3dhNlVCczBiQ0lMQ0xEWjNQLWhQaktVWkpQVjN6NkZucllIWWQ0bEJ1d3JhS2pNdEdvaU5ycERFZ0ZzNTNJelhHNGFOQl9UZVl6VDF3b2F6LXpqUnlCZW9yM0VtamxyOW1PbGY0VG1OVXc1d3VHdnpDcHBYY2RPclVPR00xRkN0X3dGX0hLMXVpUloxRXRGeWZUa2NHVzlGdnhrZTE5OE15TkVUMm1Feml2R01ETXNOdUVLY0lsV3dQUFlYQm1seUFkeURhQUdELWNzZDJOY3E2OFFqR3duYWpkdUdjZEZzRDl2azdndXZQWS1jLVVzQ2g0TE1CaWZxZHlxbV9mSU1rS2lSajQ4d0hueGlDRnV1bFBzdXZkSXFHVV94TlE1cGtwT2t3QmdDejZIZVRmaFRnVmdLRXhQSXpyQ0NMREdxMkhRbGtmbklFMUhja1lPdTlqU1c3emJzN1NSNFFmdE9Hbw==","email":"rbohne@redhat.com"},"registry.redhat.io":{"auth":"NTIxNzMzNzZ8dWhjLTFFQ3hxTUhQSkQ4TnU0cWk1NkNNU000NGh2ejpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZV001T0RKbVkyTm1PRFUwT1RaaFlUSTVaRFl6WkdFd1pUSmtaRFZoTmlKOS5sRy1DVmpLd2xKQUczMzFCY3F5dVloRXg3cHF6V2FDT1ZmdnBOSW45OGp1eDhXQXdPT0dzSGVvdlBrZU13RjJIOFdhWHc3ZEU3Snl6anppdmFodUhyN2loWlF1bjBqSGgwVnJRNHRlQjZiWE9RckNpTGpTVFZrd2g5QWJERVJzUnhwOFNpSkJrWjI3dDRicDB3SlB3WEZVZnB5T3JORjBmTkFsQU9pd2xQM1A5UThicjV1YUpHbHNpWnZyVjdkV0QwSHZuZk5GaVNMR0RKWGl1UFZqaEJKanp0ZlpBSDVKNU14eDFQdDRCZG9HeGlrUTFPdUNvdjd5bjc3Zm9EWkowX1lvRDM5Z21oWEZZMWdGQTctLTl1b1pHNmhqdFVuZy15WGRKQkkyTjZRcDV4dGRGRDJ4cTBmcklRWHE3WmVWWFJ1d0s5VmFhd3dhNlVCczBiQ0lMQ0xEWjNQLWhQaktVWkpQVjN6NkZucllIWWQ0bEJ1d3JhS2pNdEdvaU5ycERFZ0ZzNTNJelhHNGFOQl9UZVl6VDF3b2F6LXpqUnlCZW9yM0VtamxyOW1PbGY0VG1OVXc1d3VHdnpDcHBYY2RPclVPR00xRkN0X3dGX0hLMXVpUloxRXRGeWZUa2NHVzlGdnhrZTE5OE15TkVUMm1Feml2R01ETXNOdUVLY0lsV3dQUFlYQm1seUFkeURhQUdELWNzZDJOY3E2OFFqR3duYWpkdUdjZEZzRDl2azdndXZQWS1jLVVzQ2g0TE1CaWZxZHlxbV9mSU1rS2lSajQ4d0hueGlDRnV1bFBzdXZkSXFHVV94TlE1cGtwT2t3QmdDejZIZVRmaFRnVmdLRXhQSXpyQ0NMREdxMkhRbGtmbklFMUhja1lPdTlqU1c3emJzN1NSNFFmdE9Hbw==","email":"rbohne@redhat.com"}}}
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQM82o2imwpHyGVO7DxCNbdE0ZWnkp6oxdawb7/MOCT coe-muc
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAOfl+764UFbDkkxpsQYjET7ZAWoVApSf4I64L1KImoc rbohne@redhat.com
