apiVersion: v1
kind: Service
metadata:
  name: sno1-rbohne-demo
spec:
  type: LoadBalancer
  selector:
    kubevirt.io: virt-launcher
    vm.kubevirt.io/name: sno1-rbohne-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 6443
      targetPort: 6443
      name: api
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
