apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  labels:
    app: sno1-rbohne-demo
  name: sno1-rbohne-demo
spec:
  dataVolumeTemplates:
    - metadata:
        name: sno1-rbohne-demo-root
      spec:
        storage:
          accessModes:
            - ReadWriteMany
          storageClassName: ocs-storagecluster-ceph-rbd-virtualization
          resources:
            requests:
              storage: 120Gi
        source:
          blank: {}
  running: true
  template:
    metadata:
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: ""
      labels:
        kubevirt.io/domain: sno1-rbohne-demo
    spec:
      volumes:
        - name: cdrom
          persistentVolumeClaim:
            claimName: live-iso-sno
        - name: root
          dataVolume:
            name: sno1-rbohne-demo-root
      networks:
        - name: default
          pod: {}
      domain:
        cpu:
          cores: 8
        memory:
          guest: 64Gi
        resources:
          requests:
            memory: 64Gi
        devices:
          disks:
            - name: root
              bootOrder: 1
              disk:
                bus: virtio
            - name: cdrom
              bootOrder: 2
              cdrom:
                bus: sata
          interfaces:
            - bridge: {}
              name: default
