kind: ConsoleYAMLSample
apiVersion: console.openshift.io/v1
metadata:
  name: netpol-demo-simpon-default-deny
spec:
  targetResource:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
  description: |
      Default deny Network Policy
  title: Simpon Demo - Default deny
  yaml: |
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: default-deny
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
---
kind: ConsoleYAMLSample
apiVersion: console.openshift.io/v1
metadata:
  name: netpol-demo-simpon-allow-from-openshift-ingress
spec:
  targetResource:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
  description: |
      Allow from ingress
  title: Simpon Demo - Allow from ingress
  yaml: |
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
      - Ingress
---
kind: ConsoleYAMLSample
apiVersion: console.openshift.io/v1
metadata:
  name: netpol-demo-simpon-allow-same-namespace
spec:
  targetResource:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
  description: |
      Allow same namespace
  title: Simpon Demo - Allow same namespace
  yaml: |
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-same-namespace
    spec:
      podSelector: {}
      ingress:
      - from:
        - podSelector: {}
      policyTypes:
      - Ingress
---
kind: ConsoleYAMLSample
apiVersion: console.openshift.io/v1
metadata:
  name: netpol-demo-simpon-allow-from-burns
spec:
  targetResource:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
  description: |
      Allow same namespace
  title: Simpon Demo - Allow from Burns
  yaml: |
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-burns
    spec:
      podSelector: {}
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: burns
      policyTypes:
      - Ingress