---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-push-bot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-container
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "quay.io/openshift-examples": {
                "auth": "{{ ( printf "%s:%s" .username .password ) | b64enc }}"
              }
            }
          }
    name: quay-push-bot
  data:
    - secretKey: username
      remoteRef:
        key: quay-openshift-examples+cicd
        property: username
    - secretKey: password
      remoteRef:
        key: quay-openshift-examples+cicd
        property: password
