apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: coe-bridge-2001
spec:
  config: |
    {
      "name": "coe-bridge",
      "type": "bridge",
      "cniVersion": "0.3.1",
      "bridge": "coe-bridge",
      "macspoofchk": false,
      "ipam": {},
      "vlan": 2001,
      "preserveDefaultVlan": false
    }
