apiVersion: v1
baseDomain: test
compute:
  - architecture: amd64
    name: worker
    platform: {}
    replicas: 3
controlPlane:
  architecture: amd64
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: proxy
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 192.168.201.0/24
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  baremetal:
    apiVIP: 192.168.201.10
    ingressVIP: 192.168.201.11
proxy:
  httpProxy: http://192.168.201.2:3128/
  httpsProxy: http://192.168.201.2:3128/
  noProxy: 192.168.201.0/24,.apps.proxy.test,api.proxy.test
sshKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQM82o2imwpHyGVO7DxCNbdE0ZWnkp6oxdawb7/MOCT coe-muc"
pullSecret: '{"auths":{"cloud...}'
