apiVersion: clusterconfig.bohne.io/v1alpha1
kind: ClusterConfigurator
metadata:
  name: default
spec:
  secrets:
    - source_name: google-secret
      # target_namespace: openshift-config
      target_namespace: test
      target_name: google-secret
    - source_name: htpass-secret
      # target_namespace: openshift-config
      target_namespace: test
      target_name: htpass-secret
    - source_name: router-certs
      # target_namespace: openshift-ingress
      target_namespace: test
      target_name: router-certs
  oauth:
    identityProviders:
    - htpasswd:
        fileData:
          name: htpass-secret
      mappingMethod: claim
      name: Local
      type: HTPasswd
    - google:
        clientID: xxxxxxxxx
        clientSecret:
          name: google-secret
        hostedDomain: redhat.com
      mappingMethod: claim
      name: RedHatSSO
      type: Google
  ingress: 
    defaultCertificate:
      name: router-certs
  # Add fields here
  size: 3
