apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigurators.clusterconfig.bohne.io
spec:
  group: clusterconfig.bohne.io
  names:
    kind: ClusterConfigurator
    listKind: ClusterConfiguratorList
    plural: clusterconfigurators
    singular: clusterconfigurator
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
