apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "chaosprofessor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chaosprofessor.name" . }}
    helm.sh/chart: {{ include "chaosprofessor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    app.kubernetes.io/name: {{ include "chaosprofessor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Chart.Name }}
      from:
        kind: ImageStreamTag
        name: "{{ include "chaosprofessor.fullname" . }}:latest"
  - type: ConfigChange
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chaosprofessor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      strategy:
        type: Rolling
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "chaosprofessor.fullname" . }}"
          imagePullPolicy: Always
          env:
          - name: JWS_ADMIN_USERNAME
            value: {{ .Values.admin_user | default ("admin") | quote }}
          - name: JWS_ADMIN_PASSWORD
            value: {{ .Values.admin_password | default (randAlphaNum 40) | quote }}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1