kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ include "chaosprofessor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chaosprofessor.name" . }}
    helm.sh/chart: {{ include "chaosprofessor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    description: Keeps track of changes in the application image