kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "chaosprofessor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chaosprofessor.name" . }}
    helm.sh/chart: {{ include "chaosprofessor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: {{ include "chaosprofessor.fullname" . }}
