apiVersion: v1
kind: Pod
metadata:
  generateName: ubi-micro-
spec:
  containers:
    - name: ubi-micro
      image: registry.access.redhat.com/ubi9/ubi-micro:latest
      command:
        - "/bin/sh"
        - "-c"
        - "sleep infinity"
  restartPolicy: Never
