kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-configurator
subjects:
- kind: ServiceAccount
  name: cluster-configurator
  namespace: openshift-rbo-configurator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  
