apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: monty
  name: monty
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: monty
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 1024Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/fedora-cloud-container-disk-demo:latest
        name: containerdisk
      - cloudInitNoCloud:
          # User & password: fedora
          userData: |
            #cloud-config
            password: fedora
            chpasswd: { expire: False }

            packages:
              - httpd

            runcmd:
              - systemctl  enable  httpd –-now
            
        name: cloudinitdisk



