apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubevirt-csi-nodeid-ds
  namespace: kubevirt-csi-driver
spec:
  selector:
    matchLabels:
      app: kubevirt-csi-nodeid
  template:
    metadata:
      labels:
        app: kubevirt-csi-nodeid
    spec:
      serviceAccountName: kubevirt-csi-node-sa
      initContainers:
      - name: set-node-annotation
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: bitnami/kubectl:latest
        args:
        - annotate
        - node
        - $(NODENAME)
        - cluster.x-k8s.io/cluster-namespace={{ .Values.deployment.driver.infraClusterNamespace }}
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
      - name: set-node-providerid
        image: bitnami/kubectl:latest
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - patch
        - node
        - $(NODENAME)
        - --patch
        - '{"spec":{"providerID":"kubevirt://$(NODENAME)"}}'
        - --type
        - merge
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
      containers:
      - name: sleep
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: 10m