apiVersion: v1
kind: Pod
metadata:
  name: disk-bench-local
  labels:
    app: disk-bench-local
  namespace: default
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
    privileged: true
  containers:
    - name: disk-bench-local
      image: 'quay.io/openshift-examples/disk-bench:latest'
