apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace-2
commonLabels:
  tentant: tentant-2
resources:
  - ../../base/
  - udn.yaml

components:
  - ../../components/agnhost/
  - ../../components/rhel-support-tools/
  - ../../components/simple-http-server/
