apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: simpleapps.simple.application.openshift.pub
spec:
  group: simple.application.openshift.pub
  names:
    kind: SimpleApp
    listKind: SimpleAppList
    plural: simpleapps
    singular: simpleapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
