apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: coebr1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/coebr1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "coebr1",
    "type": "cnv-bridge",
    "bridge": "coebr1"
  }'
