apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: dpdk-ready
spec:
  cpu:
    # lscpu | grep NUMA
    # sh-4.4# lscpu |grep NUMA
    # NUMA node(s):         2
    # NUMA node0 CPU(s):    0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42
    # NUMA node1 CPU(s):    1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43
    isolated: 4-43
    reserved: 0-3
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      # 32GB per numa node
      - count: 64
        size: 1G
  nodeSelector:
    node-role.kubernetes.io/dpdk: ''
  realTimeKernel:
    enabled: false
  numa:
    # All guaranteed QoS containers get resources from a single NUMA node
    topologyPolicy: "single-numa-node"
  net:
    # Limit the number or IRQs to 8 (number or reserved CPUs)
    userLevelNetworking: true
