

apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: storm5-eno3
  namespace: openshift-sriov-network-operator
spec:
  resourceName: storm5eno3
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 10
  mtu: 1500
  needVhostNet: true
  numVfs: 7
  nicSelector:
    vendor: "8086"  # Intel
    deviceID: "1521" #
    # pfNames: ["<pf_name>", ...]
    # lspci -d  8086:1521 -D
    rootDevices:
      - 0000:01:00.2
#      - 0000:01:00.4
#    netFilter: "<filter_string>"
  deviceType: "vfio-pci"
  isRdma: false
#  linkType: eth # default