apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ansibleexampleoperators.bohne.io
spec:
  group: bohne.io
  names:
    kind: AnsibleExampleOperator
    listKind: AnsibleExampleOperatorList
    plural: ansibleexampleoperators
    singular: ansibleexampleoperator
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
