---
# tasks file for ansibleexampleoperator


- name: "Copy secrets"
  vars:
    source_namespace: "{{lookup('env','WATCH_NAMESPACE')}}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      data: "{{ lookup('k8s', kind='Secret', namespace=source_namespace, resource_name=item.source_name).data }}"
      metadata:
        name: "{{ item.target_name }}"
        namespace:  "{{ item.target_namespace }}"
  with_items: "{{ secrets }}"

- name: Setup oauth
  k8s: 
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec: "{{ oauth }}"

- name: Patch router
  k8s:
    state: present
    merge_type: merge
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec: "{{ ingress }}"
            