---
# tasks file for ansibleexampleoperator

- name: "Copy secrets"
  vars:
    source_namespace: "{{lookup('env','WATCH_NAMESPACE')}}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      data: "{{ lookup('k8s', kind='Secret', namespace=source_namespace, resource_name=item.source_name).data }}"
      metadata:
        name: "{{ item.target_name }}"
        namespace:  "{{ item.target_namespace }}"
  with_items: "{{ secrets }}"

- debug: msg="Oauth spec {{ _clusterconfig_bohne_io_clusterconfigurator.spec.oauth }}"

- name: Setup oauth
  k8s: 
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec: "{{ _clusterconfig_bohne_io_clusterconfigurator.spec.oauth }}"

- debug: msg="Ingress spec {{ _clusterconfig_bohne_io_clusterconfigurator.spec.ingress }}"

- name: Patch router
  k8s:
    state: present
    merge_type: merge
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec: "{{ _clusterconfig_bohne_io_clusterconfigurator.spec.ingress }}"

- name: Cluster admins
  k8s:
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "cluster-configurator-cluster-admin-{{ item }}"
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: "{{ item }}"
      roleRef:
        kind: ClusterRole
        name: cluster-admin
  with_items: "{{ cluster_admins }}"
