nameOverride: examples-stage-openshift-pub
replicaCount: 1
image:
  repository: quay.io/openshift-examples/web
  pullPolicy: Always
  tag: sha256:96eb0cbd1a0b9a1930b1f098c395fc32876cc23e511097f3b725a3e6f90da612

route:
  hostOverride: examples-stage.openshift.pub
  annotations:
    kubernetes.io/tls-acme: 'true'
