nameOverride: examples-stage-openshift-pub
replicaCount: 1
image:
  repository: quay.io/openshift-examples/web
  pullPolicy: Always
  tag: sha256:618ccaf0769b6a927143443e1c5a2a2fac498930f7ba8db9c703b4b4b5d8bf8d

route:
  hostOverride: examples-stage.openshift.pub
  annotations:
    kubernetes.io/tls-acme: 'true'
