nameOverride: examples-stage-openshift-pub
replicaCount: 1
image:
  repository: quay.io/openshift-examples/web
  pullPolicy: Always
  tag: devel

route:
  hostOverride: examples-stage.openshift.pub
  annotations:
    kubernetes.io/tls-acme: 'true'
