nameOverride: examples-stage-openshift-pub
replicaCount: 1
image:
  repository: quay.io/openshift-examples/web
  pullPolicy: Always
  tag: sha256:a800725210c340ac0a777e8d69738e6c4da889406f52315a41ebbd8ce902895f

route:
  hostOverride: examples-stage.openshift.pub
  annotations:
    kubernetes.io/tls-acme: 'true'
