nameOverride: examples-stage-openshift-pub
replicaCount: 1
image:
  repository: quay.io/openshift-examples/web
  pullPolicy: Always
  tag: sha256:d9167599512d0323f2e93a9d718e71e5d9481bad1b2fadbf46b8979778dea190

route:
  hostOverride: examples-stage.openshift.pub
  annotations:
    kubernetes.io/tls-acme: 'true'
