nameOverride: examples-stage-openshift-pub
replicaCount: 1
image:
  repository: quay.io/openshift-examples/web
  pullPolicy: Always
  tag: sha256:975f7301ac4b8f5532e1e90593f8602c7055191c855754ce269b0d7802d4abd9

route:
  enabled: false
  hostOverride: examples-stage.openshift.pub
  annotations:
    kubernetes.io/tls-acme: 'true'

certificate:
  enabled: true
  commonName: "examples-stage.openshift.pub"
  dnsNames:
    - "examples-stage.openshift.pub"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-openshift-pub
  secretName: examples-stage-openshift-pub

ingress:
  enabled: true
  className: ""
  annotations:
    route.openshift.io/termination: "edge"
  hosts:
    - host: examples-stage.openshift.pub
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: examples-stage-openshift-pub
      hosts:
        - examples-stage.openshift.pub
