apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: storm5-rbohne-sriov-test-eno3
  namespace: openshift-sriov-network-operator
spec:
  resourceName: storm5eno3
  networkNamespace: rbohne-sriov-test
  vlan: 100
  vlanQoS: 1
  trust: "on"
  spoofChk: "off"
  # ipam: |-
  #maxTxRate: 100
  #   {
  #     "type": "static",
  #     "addresses": [
  #       {
  #         "address": "127.0.0.100/32"
  #       }
  #     ]
  #   }
# sh-4.4# ip link set eno3 vf 0 state enable
# RTNETLINK answers: Operation not supported
#  linkState: auto
#  capabilities: '{ "ips": true }'