apiVersion: v1
baseDomain: coe.muc.redhat.com
compute:
  - name: worker
    replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: sno-on-ocpv
networking:
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.128.0.0/14
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.31.0.0/16
platform:
  none: {}
bootstrapInPlace:
  installationDisk: /dev/vda
pullSecret: |
  {"auths":{"cloud.openshift.com":'....
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQM82o2imwpHyGVO7DxCNbdE0ZWnkp6oxdawb7/MOCT coe-muc
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAOfl+764UFbDkkxpsQYjET7ZAWoVApSf4I64L1KImoc rbohne@redhat.com
