apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: monty
  name: monty
spec:
  to:
    kind: Service
    name: monty
    weight: 100
  port:
    targetPort: 80-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None