apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: web
  namespace: examples-openshift-pub
spec:
  url: "https://github.com/openshift-examples/web"
  params:
    - name: clone_url
      value: git@github.com:openshift-examples/web.git
