apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJSON6902:
- target:
    group: examples.openshift.pub
    version: v1
    kind: ExamplesOpenShiftPub
    name: test
  patch: |-
    - op: add
      path: /spec/list/-1
      value: "second-element"