apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: simple-https
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: simple-https
  validation:
    # System do not include openshift service serving root ca.
    # wellKnownCACertificates: "System"
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: my-openshift-service-ca.crt
    hostname: simple-https.test-app.svc
