---
ansible-navigator:
  execution-environment:
    # container-options:
      # - --net=host
    image: quay.io/openshift-examples/kubevirt-ansible-ee:202312291719
    environment-variables:
      pass:
        - KUBECONFIG
        - K8S_AUTH_KUBECONFIG
    volume-mounts:
      # Ugly as hell.. I don't know a better solution yet
      - src: "/var/home/rbohne/.kube"
        dest: "/var/home/rbohne/.kube"
        options: "Z"
        # Just needed for the upload
      - src: "/var/home/rbohne/Downloads"
        dest: "/var/home/rbohne/Downloads"
        options: "Z"
  logging:
    level: info
  mode: stdout
  playbook-artifact:
    enable: true
    save-as: /tmp/example-openshift-kubevirt-{playbook_name}-artifact-{time_stamp}.json
