---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    namespace: demo-cluster-disco
  tasks:

    - name: Prepare rootdisk
      community.kubevirt.kubevirt_pvc:
        name: beryllium-rootdisk
        namespace: "{{ namespace  }}"
        storage_class_name: coe-netapp-nas
        size: 80Gi
        access_modes:
          - ReadWriteMany
        cdi_source:
          blank: yes

    - name: VM
      community.kubevirt.kubevirt_vm:
        state: running
        name: beryllium
        namespace: "{{ namespace }}"
        memory: 4Gi
        cpu_cores: 4
        disks:
          - name: root
            bootOrder: 1
            volume:
              persistentVolumeClaim:
                claimName: beryllium-rootdisk
            disk:
              bus: virtio
          - name: cdrom
            bootOrder: 2
            volume:
              persistentVolumeClaim:
                claimName: beryllium-1-i386-hybrid
            cdrom:
              bus: sata
