---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    namespace: demo-cluster-disco
  tasks:

    - name: VM
      kubevirt.core.kubevirt_vm:
        state: present
        running: true # default
        wait: true
        name: beryllium
        namespace: "{{ namespace }}"

        data_volume_templates:
          - metadata:
              name: beryllium-root
            spec:
              storage:
                accessModes:
                  - ReadWriteMany
                storageClassName: coe-netapp-nas
                resources:
                  requests:
                    storage: 80Gi
              source:
                blank: {}

        spec:
          volumes:
            - name: cdrom
              persistentVolumeClaim:
                claimName: beryllium-1-i386-hybrid
            - name: root
              dataVolume:
                name: beryllium-root
          networks:
            - name: coe
              multus:
                networkName: coe-bridge
            - name: disco
              multus:
                networkName: coe-br-vlan-69
          domain:
            cpu:
              cores: 4
            memory:
              guest: 8Gi
            resources:
              requests:
                memory: 8Gi
            devices:
              disks:
                - name: root
                  bootOrder: 1
                  disk:
                    bus: virtio
                - name: cdrom
                  bootOrder: 2
                  cdrom:
                    bus: sata
              interfaces:
                - bridge: {}
                  # macAddress: 02:d8:6d:00:00:12
                  model: virtio
                  name: coe
                - bridge: {}
                  # macAddress: 02:d8:6d:00:00:13
                  model: virtio
                  name: disco
