kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "hpa-demo.fullname" . }}
  labels:
{{ include "hpa-demo.labels" . | indent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "hpa-demo.fullname" . }}