---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: extra-worker-1
  namespace: stormshift-ocp1-infra
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: extra-worker-1-root
      spec:
        source:
          blank: {}
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 120Gi
          storageClassName: coe-netapp-san
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: root
            - bootOrder: 2
              cdrom:
                bus: sata
              name: cdrom
          interfaces:
            - bridge: {}
              macAddress: '0E:C0:EF:20:69:4B'
              model: virtio
              name: coe
            - bridge: {}
              macAddress: '0E:C0:EF:20:69:4C'
              model: virtio
              name: coe2
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 16Gi
        resources:
          limits:
            memory: 16706Mi
          requests:
            memory: 16Gi
      networks:
        - multus:
            networkName: coe-bridge
          name: coe
        - multus:
            networkName: coe-bridge
          name: coe2
      volumes:
        - name: cdrom
          persistentVolumeClaim:
            claimName: extra-worker-1-iso
        - dataVolume:
            name: extra-worker-1-root
          name: root
