apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    type: static-nfs-2e4c62a0f0
  name: coe-isos
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Gi
  nfs:
    path: /coe_iso
    server: 10.32.97.1
  persistentVolumeReclaimPolicy: Retain

