apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: examples-stage-openshift-pub
spec:
  destination:
    namespace: production
    server: https://api.rh-us-east-1.openshift.com
  project: default
  source:
    helm:
      valueFiles:
        - ../devel.value.yaml
    path: deploy/openshift-examples-simple/
    repoURL: https://github.com/openshift-examples/web
    targetRevision: devel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
