apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-2
spec:
  topology: Layer3
  layer3:
    role: Primary
    subnets:
      - cidr: 10.255.0.0/16
        hostSubnet: 24
    ipam:
      lifecycle: Persistent
