apiVersion: aaq.kubevirt.io/v1alpha1
kind: ApplicationAwareClusterResourceQuota
metadata:
  name: example-resource-quota
spec:
  quota:
    hard:
      requests.cpu/vmi: "20"
      requests.memory/vmi: 20Gi
      limits.cpu/vmi: "20"
      limits.memory/vmi: 20Gi
  selector:
    annotations: null
    labels:
      matchLabels:
        application-aware-quota/enable-gating: ""
