apiVersion: aaq.kubevirt.io/v1alpha1
kind: ApplicationAwareResourceQuota
metadata:
  name: example-resource-quota
spec:
  hard:
    requests.cpu/vmi: "5"
    requests.memory/vmi: 10Gi
    limits.cpu/vmi: "10"
    limits.memory/vmi: 20Gi
