apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: green
resources:
  - ../../base/
  - udn.yaml

components:
  - ../../components/agnhost/
  - ../../components/rhel-support-tools/
