apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: namespace-scoped
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - 198.51.100.0/24
    ipam:
      lifecycle: Persistent
