apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-external-dns

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - namespace.yaml
  - serviceaccount.yaml
