---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jar-init-container-example
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jar-init-container
  template:
    metadata:
      labels:
        app: jar-init-container
    spec:
      volumes:
       - name: app
         emptyDir: {}
      initContainers:
      - name: copy-jar
        image: quay.io/openshift-examples/jar-deploy-example:initContainer
        volumeMounts:
          - name: app
            mountPath: /app
        command:
          - sh
          - -c
          - |
            cp -v /deployments/undertow-servlet.jar /app/undertow-servlet.jar

      containers:
      - name: app
        image: registry.access.redhat.com/ubi8/openjdk-11-runtime
        volumeMounts:
          - name: app
            mountPath: /app
        command:
          - java
          - -jar
          - /app/undertow-servlet.jar
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jar-init-container
  name: jar-init-container
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jar-init-container
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: jar-init-container
  name: jar-init-container
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: jar-init-container
    weight: null

