apiVersion: v1
kind: ServiceAccount
metadata:
  name: privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-to-privileged
subjects:
  - kind: ServiceAccount
    name: privileged
roleRef:
  kind: Role
  name: privileged
  apiGroup: rbac.authorization.k8s.io