---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: check-and-test-deployment
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[pull_request]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main,devel]"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/task: "git-clone"

    # Use maven task from hub
    # pipelinesascode.tekton.dev/task-1: "[pre-commit]"

    # You can add more tasks in here to reuse, browse the one you like from here
    # https://hub.tekton.dev/
    # example:
    # pipelinesascode.tekton.dev/task-2: "[github-add-labels]"
    pipelinesascode.tekton.dev/task-2: "[.tekton/task/github-add-labels.yaml]"
    pipelinesascode.tekton.dev/task-3: "[.tekton/task/github-add-comment.yaml]"

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: pull_request_number
      value: "{{ pull_request_number }}"
    - name: git_auth_secret
      value: "{{ git_auth_secret }}"
    - name: source_branch
      value: "{{source_branch}}"
    - name: target_branch
      value: "{{target_branch}}"
    - name: pr_base_sha
      value: "{{ body.pull_request.base.sha }}"
    - name: pr_commits
      value: "{{ body.pull_request.commits }}"

  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
  # taskRunSpecs:
  #   - pipelineTaskName: pre-commit
  #     podTemplate:
  #       nodeSelector:
  #         kubernetes.io/arch: amd64
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: pull_request_number
      - name: git_auth_secret
      - name: pr_base_sha
      - name: pr_commits
    workspaces:
      - name: source
      - name: basic-auth
    tasks:

      # - name: debug
      #   workspaces:
      #     - name: source
      #       workspace: source
      #   params:
      #     - name: pr_base_sha
      #       value: $(params.pr_base_sha)
      #   taskSpec:
      #     steps:
      #       - name: debug
      #         env:
      #           - name: PR_BASE_SHA
      #             value: $(params.pr_base_sha)
      #         image: registry.access.redhat.com/ubi9/ubi
      #         script: |
      #           #!/usr/bin/env python3
      #           import json
      #           import pprint
      #           pp = pprint.PrettyPrinter(indent=4)
      #           pp.pprint(json.loads("""{{ body }}"""))
      #           exit(0)

      - name: fetch-repository-pr
        # runAfter:
        #   - debug
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: git-clone
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: URL
            value: $(params.repo_url)
          - name: REVISION
            value: $(params.revision)
          - name: DEPTH
            value: 0
          - name: SUBDIRECTORY
            value: pr

      - name: pre-commit
        runAfter:
          - fetch-repository-pr
        workspaces:
          - name: source
            workspace: source
        params:
          - name: pr_commit
            value: $(tasks.fetch-repository-pr.results.COMMIT)
          - name: pr_commits
            value: $(params.pr_commits)
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: pre-commit
              image: quay.io/openshift-examples/builder:devel
              imagePullPolicy: Always
              workingDir: $(workspaces.source.path)/pr
              securityContext:
                runAsNonRoot: true
                runAsUser: 65532
              env:
                - name: PR_COMMITS
                  value: $(params.pr_commits)
                - name: PR_COMMIT
                  value: $(params.pr_commit)
                - name: WORKSPACE
                  value: $(workspaces.source.path)
              script: |
                set -euxo pipefail

                git config --global --add safe.directory ${WORKSPACE}/pr

                echo -e ' 💀 There was an error during pre-commit / linter:\n\n```' \
                  > ${WORKSPACE}/notify-linter-on-failure.txt

                pre-commit run --color=never \
                  --from-ref HEAD~${PR_COMMITS} \
                  --to-ref ${PR_COMMIT} \
                | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" \
                | tee -a ${WORKSPACE}/notify-linter-on-failure.txt

                RC=$?
                echo "Return code $RC"

                echo -e '\n```\n' \
                  > ${WORKSPACE}/notify-linter-on-failure.txt

                exit $?

      - name: github-add-labels
        runAfter:
          - pre-commit
        taskRef:
          name: github-add-labels
        params:
          - name: REQUEST_URL
            value: "$(params.repo_url)/pull/$(params.pull_request_number)"
          - name: LABELS
            value:
              - ok-for-test-deployment
          - name: PAC_GITHUB_SECRET
            value: "$(params.git_auth_secret)"

      - name: wait-for-imagestream
        params:
          - name: SCRIPT
            value: |
              while true; do
                oc get imagestream/pr-$(params.pull_request_number) && exit 0 ;
                sleep 5;
              done;
          - name: VERSION
            value: latest
        runAfter:
          - github-add-labels
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: openshift-client
            - name: namespace
              value: openshift-pipelines
        workspaces:
      - name: build-builder-image
        params:
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/pr-$(params.pull_request_number):builder
          - name: DOCKERFILE
            value: ./pr/builder.Containerfile
          - name: TLSVERIFY
            value: 'false'
          - name: CONTEXT
            value: 'pr/'
        runAfter:
          - wait-for-imagestream
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: buildah
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: source
            workspace: source

      - name: build-web-image
        params:
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/pr-$(params.pull_request_number):latest
          - name: DOCKERFILE
            value: ./pr/Containerfile
          - name: BUILD_EXTRA_ARGS
            value: "--build-arg BUILDER_IMAGE=image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/pr-$(params.pull_request_number):builder"
          - name: TLSVERIFY
            value: 'false'
          - name: CONTEXT
            value: 'pr/'
        runAfter:
          - build-builder-image
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: buildah
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: source
            workspace: source

      - name: wait-for-route-and-notify
        runAfter:
          - build-web-image
        workspaces:
          - name: source
            workspace: source
        params:
          - name: pull_request_number
            value: "$(params.pull_request_number)"
        taskSpec:
          params:
            - name: pull_request_number
              type: string
          workspaces:
            - name: source
          steps:
            - name: pre-commit
              image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
              workingDir: $(workspaces.source.path)
              script: |
                #!/usr/bin/env bash
                set -euxo pipefail

                while true; do
                  oc get routes/pr-$(params.pull_request_number) && break ;
                  sleep 5;
                done;

                oc rollout status deployment/pr-$(params.pull_request_number)

                oc get routes/pr-$(params.pull_request_number) \
                  -o go-template='💻 Deployed & available at {{"\n"}}🌎 https://{{ .spec.host}}{{"\n"}}' \
                  | tee $(workspaces.source.path)/notify-deployment.txt

      - name: notify-deployment
        runAfter:
          - wait-for-route-and-notify
        workspaces:
          - name: comment-file
            workspace: source
        params:
          - name: REQUEST_URL
            value: "$(params.repo_url)/pull/$(params.pull_request_number)"
          - name: PAC_GITHUB_SECRET
            value: "$(params.git_auth_secret)"
          - name: COMMENT_OR_FILE
            value: "notify-deployment.txt"
        taskRef:
          name: github-add-comment
    finally:
      - name: notify-linter-on-failure
        workspaces:
          - name: comment-file
            workspace: source
        when:
          - input: $(tasks.pre-commit.status)
            operator: in
            values: ["Failed"]
        params:
          - name: REQUEST_URL
            value: "$(params.repo_url)/pull/$(params.pull_request_number)"
          - name: PAC_GITHUB_SECRET
            value: "$(params.git_auth_secret)"
          - name: COMMENT_OR_FILE
            value: "notify-linter-on-failure.txt"
        taskRef:
          name: github-add-comment

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    # This workspace will inject secret to help the git-clone task to be able to
    # checkout the private repositories
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
