---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release-tag
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    # pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-event: "[push]"
    # The branch or tag we are targeting (ie: main, refs/tags/*)
    # pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/*,main,devel,refactor-development]"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/task: "git-clone"

    # Use maven task from hub
    # pipelinesascode.tekton.dev/task-1: "[pre-commit]"

    # You can add more tasks in here to reuse, browse the one you like from here
    # https://hub.tekton.dev/
    # example:
    pipelinesascode.tekton.dev/task-1: "[buildah]"
    # pipelinesascode.tekton.dev/task-2: "[.tekton/task/github-add-labels.yaml]"
    # pipelinesascode.tekton.dev/task-3: "[.tekton/task/github-add-comment.yaml]"

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    # - name: pull_request_number
    #   value: "{{ pull_request_number }}"
    # - name: git_auth_secret
    #   value: "{{ git_auth_secret }}"
    - name: source_branch
      value: '{{ source_branch }}'
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: source_branch
      # - name: pull_request_number
      # - name: git_auth_secret
    workspaces:
      - name: source
      - name: basic-auth
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      # Customize this task if you like, or just do a taskRef
      # to one of the hub task.
      - name: tag
        params:
          - name: source_branch
            value: $(params.source_branch)
        taskSpec:
          results:
            - name: name
              descripte: Clean tag based on source_branch
          steps:
            - name: transform-tag
              image: registry.access.redhat.com/ubi9/ubi-micro:latest
              script: |
                set -x
                SOURCE_BRANCH="$(params.source_branch)"
                echo -n ${SOURCE_BRANCH#refs/tags/} | tee $(results.name.path)

      - name: build-builder-image
        params:
          - name: IMAGE
            value: quay.io/openshift-examples/builder:$(tasks.tag.results.name)
          - name: DOCKERFILE
            value: ./builder.Containerfile
          # - name: BUILD_EXTRA_ARGS
          #   value: '--target builder'
        runAfter:
          - tag
          - fetch-repository
        taskRef:
          kind: ClusterTask
          name: buildah
        workspaces:
          - name: source
            workspace: source

      - name: build-web-image
        params:
          - name: IMAGE
            value: 'quay.io/openshift-examples/web:$(tasks.tag.results.name)'
          - name: DOCKERFILE
            value: ./Containerfile
          - name: BUILD_EXTRA_ARGS
            value: "--build-arg BUILDER_IMAGE=quay.io/openshift-examples/builder:$(tasks.tag.results.name)"
          # https://access.redhat.com/solutions/6843481
          - name: PUSH_EXTRA_ARGS
            value: "--format v2s2"
        runAfter:
          - build-builder-image
        taskRef:
          kind: ClusterTask
          name: buildah
        workspaces:
          - name: source
            workspace: source
          - name: dockerconfig

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    # This workspace will inject secret to help the git-clone task to be able to
    # checkout the private repositories
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
