apiVersion: v1
kind: DeploymentConfig
metadata:
  name: busybox-tty
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig:  busybox-tty
    spec:
      containers:
      - name: nginx
        image: nginx
      - image: busybox
        name:  busybox-tty
        command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        stdin: true
        tty: true
  triggers:
  - type: ConfigChange
