apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace-1
commonLabels:
  tentant: tentant-1
resources:
  - ../../base/
  - udn.yaml

components:
  - git@github.com:openshift-examples/kustomize.git/components/agnhost?ref=2025-06-25
  - git@github.com:openshift-examples/kustomize.git/components/rhel-support-tools/?ref=2025-06-25
  - git@github.com:openshift-examples/kustomize.git/components/simple-http-server/?ref=2025-06-25
  - git@github.com:openshift-examples/kustomize.git/components/simple-httpd-vm/?ref=2025-06-25
