apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace-1
commonLabels:
  tentant: tentant-1
resources:
  - ../../base/
  - udn.yaml

components:
  - ../../components/agnhost/
  - ../../components/rhel-support-tools/
  - ../../components/simple-http-server/
  - ../../components/simple-httpd-vm/
