apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-1
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - 192.0.2.0/24
    ipam:
      lifecycle: Persistent
