apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: coe-2003
  namespace: metallb-system
spec:
  addresses:
    - 192.168.203.10-192.168.203.19
  autoAssign: true
  avoidBuggyIPs: false
