apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: lldpd
  namespace: infra-lldpd
spec:
  source:
    type: Git
    git:
      url: https://github.com/openshift-examples/web
    contextDir: content/networking/lldp
  strategy:
    name: buildah
    kind: ClusterBuildStrategy
  paramValues:
    - name: dockerfile
      value: Containerfile
  volumes:
    - csi:
        driver: csi.sharedresource.openshift.io
        readOnly: true
        volumeAttributes:
          sharedSecret: etc-pki-entitlement
      name: etc-pki-entitlement
  output:
    image: image-registry.openshift-image-registry.svc:5000/infra-lldpd/lldpd:latest
