---
apiVersion: v1
kind: Service
metadata:
  name: win-webserver-2004
  labels:
    app: win-webserver-2004
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: win-webserver-2004
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: win-webserver-2004
  name: win-webserver-2004
spec:
  port:
    targetPort: 80
  to:
    kind: "Service"
    name: win-webserver-2004
    weight: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver-2004
  name: win-webserver-2004
spec:
  selector:
    matchLabels:
      app: win-webserver-2004
  replicas: 3
  template:
    metadata:
      labels:
        app: win-webserver-2004
      name: win-webserver-2004
    spec:
      tolerations:
      - key: "os"
        value: "Windows"
        Effect: "NoSchedule"
      containers:
      - name: windowswebserver
        image: mcr.microsoft.com/windows/servercore:2004
        imagePullPolicy: IfNotPresent
        command:
        - powershell.exe
        - -command
        - $listener = New-Object System.Net.HttpListener; $listener.Prefixes.Add('http://*:80/'); $listener.Start();Write-Host('Listening at http://*:80/'); while ($listener.IsListening) { $context = $listener.GetContext(); $response = $context.Response; $content='<html><body><H1>Windows Container Web Server</H1></body></html>'; $buffer = [System.Text.Encoding]::UTF8.GetBytes($content); $response.ContentLength64 = $buffer.Length; $response.OutputStream.Write($buffer, 0, $buffer.Length); $response.Close(); };
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
        node.kubernetes.io/windows-build: 10.0.19041
