apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: san
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: coe-netapp-san
  volumeMode: Filesystem
