# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'PR Close - Deletion'
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-delete:
    permissions:
      actions: read # Only required for private GitHub Repo
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Deploy deletion Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages/delete@v2.3.2
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}